version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.11   # for pip install of SAM CLI
    commands:
      - echo "Installing SAM CLI..."
      - pip install --upgrade aws-sam-cli
      - node -v && npm -v && sam --version
  pre_build:
    commands:
      - echo "Installing Lambda deps..."
      - cd src && npm ci --omit=dev && cd ..
  build:
    commands:
      - echo "Build started on $(date)"
      # (Optional) run your tests here if you have any, e.g. npm test
  post_build:
    commands:
      - sam validate
      - |
        sam package \
          --s3-bucket dk-bucket-915116534218 \
          --template-file template.yml \
          --output-template-file outputSamTemplate.yml
      - echo "Build completed on $(date)"

artifacts:
  files:
    - outputSamTemplate.yml
    - template.yml