version = 0.1

[default]
[default.global.parameters]
stack_name = "dk-UploadsNotificationFunction"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = false
s3_bucket = "dk-bucket-915116534218"
# You can bake parameters in here, or pass them via CLI:
# parameter_overrides = "TopicArn=arn:aws:sns:REGION:ACCOUNT:dk-UploadsNotificationTopic SQSQueueArn=arn:aws:sqs:REGION:ACCOUNT:dk-UploadsNotificationQueue FunctionName=dk-UploadsNotificationFunction"

[default.package.parameters]
resolve_s3 = false

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"